# Cleaning Fifa-18 Dataset

Dataset source: https://www.kaggle.com/thec03u5/fifa-18-demo-player-dataset

In [11]:
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt

In [12]:
df = pd.read_csv('CompleteDataset.csv')

E:\Program Files\Anaconda3\envs\bigdata\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (23,35) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [13]:
pd.set_option('display.max_columns',None)

In [14]:
df.head()

,Unnamed: 0,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,Value,Wage,Special,Acceleration,Aggression,Agility,Balance,Ball control,Composure,Crossing,Curve,Dribbling,Finishing,Free kick accuracy,GK diving,GK handling,GK kicking,GK positioning,GK reflexes,Heading accuracy,Interceptions,Jumping,Long passing,Long shots,Marking,Penalties,Positioning,Reactions,Short passing,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,CAM,CB,CDM,CF,CM,ID,LAM,LB,LCB,LCM,LDM,LF,LM,LS,LW,LWB,Preferred Positions,RAM,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST
0,0,Cristiano Ronaldo,32,https://cdn.sofifa.org/48/18/players/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Real Madrid CF,https://cdn.sofifa.org/24/18/teams/243.png,€95.5M,€565K,2228,89,63,89,63,93,95,85,81,91,94,76,7,11,15,14,11,88,29,95,77,92,22,85,95,96,83,94,23,91,92,31,80,85,88,89.0,53.0,62.0,91.0,82.0,20801,89.0,61.0,53.0,82.0,62.0,91.0,89.0,92.0,91.0,66.0,ST LW,89.0,61.0,53.0,82.0,62.0,91.0,89.0,92.0,91.0,66.0,92.0
1,1,L. Messi,30,https://cdn.sofifa.org/48/18/players/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,93,93,FC Barcelona,https://cdn.sofifa.org/24/18/teams/241.png,€105M,€565K,2154,92,48,90,95,95,96,77,89,97,95,90,6,11,15,14,8,71,22,68,87,88,13,74,93,95,88,85,26,87,73,28,59,90,85,92.0,45.0,59.0,92.0,84.0,158023,92.0,57.0,45.0,84.0,59.0,92.0,90.0,88.0,91.0,62.0,RW,92.0,57.0,45.0,84.0,59.0,92.0,90.0,88.0,91.0,62.0,88.0
2,2,Neymar,25,https://cdn.sofifa.org/48/18/players/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,94,Paris Saint-Germain,https://cdn.sofifa.org/24/18/teams/73.png,€123M,€280K,2100,94,56,96,82,95,92,75,81,96,89,84,9,9,15,15,11,62,36,61,75,77,21,81,90,88,81,80,33,90,78,24,53,80,83,88.0,46.0,59.0,88.0,79.0,190871,88.0,59.0,46.0,79.0,59.0,88.0,87.0,84.0,89.0,64.0,LW,88.0,59.0,46.0,79.0,59.0,88.0,87.0,84.0,89.0,64.0,84.0
3,3,L. Suárez,30,https://cdn.sofifa.org/48/18/players/176580.png,Uruguay,https://cdn.sofifa.org/flags/60.png,92,92,FC Barcelona,https://cdn.sofifa.org/24/18/teams/241.png,€97M,€510K,2291,88,78,86,60,91,83,77,86,86,94,84,27,25,31,33,37,77,41,69,64,86,30,85,92,93,83,87,38,77,89,45,80,84,88,87.0,58.0,65.0,88.0,80.0,176580,87.0,64.0,58.0,80.0,65.0,88.0,85.0,88.0,87.0,68.0,ST,87.0,64.0,58.0,80.0,65.0,88.0,85.0,88.0,87.0,68.0,88.0
4,4,M. Neuer,31,https://cdn.sofifa.org/48/18/players/167495.png,Germany,https://cdn.sofifa.org/flags/21.png,92,92,FC Bayern Munich,https://cdn.sofifa.org/24/18/teams/21.png,€61M,€230K,1493,58,29,52,35,48,70,15,14,30,13,11,91,90,95,91,89,25,30,78,59,16,10,47,12,85,55,25,11,61,44,10,83,70,11,NaN,NaN,NaN,NaN,NaN,167495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df = df.rename(columns={'Unnamed: 0': 'Index'})
df.head()

,Index,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,Value,Wage,Special,Acceleration,Aggression,Agility,Balance,Ball control,Composure,Crossing,Curve,Dribbling,Finishing,Free kick accuracy,GK diving,GK handling,GK kicking,GK positioning,GK reflexes,Heading accuracy,Interceptions,Jumping,Long passing,Long shots,Marking,Penalties,Positioning,Reactions,Short passing,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,CAM,CB,CDM,CF,CM,ID,LAM,LB,LCB,LCM,LDM,LF,LM,LS,LW,LWB,Preferred Positions,RAM,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST
0,0,Cristiano Ronaldo,32,https://cdn.sofifa.org/48/18/players/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Real Madrid CF,https://cdn.sofifa.org/24/18/teams/243.png,€95.5M,€565K,2228,89,63,89,63,93,95,85,81,91,94,76,7,11,15,14,11,88,29,95,77,92,22,85,95,96,83,94,23,91,92,31,80,85,88,89.0,53.0,62.0,91.0,82.0,20801,89.0,61.0,53.0,82.0,62.0,91.0,89.0,92.0,91.0,66.0,ST LW,89.0,61.0,53.0,82.0,62.0,91.0,89.0,92.0,91.0,66.0,92.0
1,1,L. Messi,30,https://cdn.sofifa.org/48/18/players/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,93,93,FC Barcelona,https://cdn.sofifa.org/24/18/teams/241.png,€105M,€565K,2154,92,48,90,95,95,96,77,89,97,95,90,6,11,15,14,8,71,22,68,87,88,13,74,93,95,88,85,26,87,73,28,59,90,85,92.0,45.0,59.0,92.0,84.0,158023,92.0,57.0,45.0,84.0,59.0,92.0,90.0,88.0,91.0,62.0,RW,92.0,57.0,45.0,84.0,59.0,92.0,90.0,88.0,91.0,62.0,88.0
2,2,Neymar,25,https://cdn.sofifa.org/48/18/players/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,94,Paris Saint-Germain,https://cdn.sofifa.org/24/18/teams/73.png,€123M,€280K,2100,94,56,96,82,95,92,75,81,96,89,84,9,9,15,15,11,62,36,61,75,77,21,81,90,88,81,80,33,90,78,24,53,80,83,88.0,46.0,59.0,88.0,79.0,190871,88.0,59.0,46.0,79.0,59.0,88.0,87.0,84.0,89.0,64.0,LW,88.0,59.0,46.0,79.0,59.0,88.0,87.0,84.0,89.0,64.0,84.0
3,3,L. Suárez,30,https://cdn.sofifa.org/48/18/players/176580.png,Uruguay,https://cdn.sofifa.org/flags/60.png,92,92,FC Barcelona,https://cdn.sofifa.org/24/18/teams/241.png,€97M,€510K,2291,88,78,86,60,91,83,77,86,86,94,84,27,25,31,33,37,77,41,69,64,86,30,85,92,93,83,87,38,77,89,45,80,84,88,87.0,58.0,65.0,88.0,80.0,176580,87.0,64.0,58.0,80.0,65.0,88.0,85.0,88.0,87.0,68.0,ST,87.0,64.0,58.0,80.0,65.0,88.0,85.0,88.0,87.0,68.0,88.0
4,4,M. Neuer,31,https://cdn.sofifa.org/48/18/players/167495.png,Germany,https://cdn.sofifa.org/flags/21.png,92,92,FC Bayern Munich,https://cdn.sofifa.org/24/18/teams/21.png,€61M,€230K,1493,58,29,52,35,48,70,15,14,30,13,11,91,90,95,91,89,25,30,78,59,16,10,47,12,85,55,25,11,61,44,10,83,70,11,NaN,NaN,NaN,NaN,NaN,167495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17981 entries, 0 to 17980
Data columns (total 75 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Index                17981 non-null  int64
 1   Name                 17981 non-null  object
 2   Age                  17981 non-null  int64
 3   Photo                17981 non-null  object
 4   Nationality          17981 non-null  object
 5   Flag                 17981 non-null  object
 6   Overall              17981 non-null  int64
 7   Potential            17981 non-null  int64
 8   Club                 17733 non-null  object
 9   Club Logo            17981 non-null  object
 10  Value                17981 non-null  object
 11  Wage                 17981 non-null  object
 12  Special              17981 non-null  int64
 13  Acceleration         17981 non-null  object
 14  Aggression           17981 non-null  object
 15  Agility              17981 non-null  object
 16  Balance              17981 non-null  object
 17  Ball control         17981 non-null  object
 18  Composure            17981 non-null  object
 19  Crossing             17981 non-null  object
 20  Curve                17981 non-null  object
 21  Dribbling            17981 non-null  object
 22  Finishing            17981 non-null  object
 23  Free kick accuracy   17981 non-null  object
 24  GK diving            17981 non-null  object
 25  GK handling          17981 non-null  object
 26  GK kicking           17981 non-null  object
 27  GK positioning       17981 non-null  object
 28  GK reflexes          17981 non-null  object
 29  Heading accuracy     17981 non-null  object
 30  Interceptions        17981 non-null  object
 31  Jumping              17981 non-null  object
 32  Long passing         17981 non-null  object
 33  Long shots           17981 non-null  object
 34  Marking              17981 non-null  object
 35  Penalties            17981 non-null  object
 36  Positioning          17981 non-null  object
 37  Reactions            17981 non-null  object
 38  Short passing        17981 non-null  object
 39  Shot power           17981 non-null  object
 40  Sliding tackle       17981 non-null  object
 41  Sprint speed         17981 non-null  object
 42  Stamina              17981 non-null  object
 43  Standing tackle      17981 non-null  object
 44  Strength             17981 non-null  object
 45  Vision               17981 non-null  object
 46  Volleys              17981 non-null  object
 47  CAM                  15952 non-null  float64
 48  CB                   15952 non-null  float64
 49  CDM                  15952 non-null  float64
 50  CF                   15952 non-null  float64
 51  CM                   15952 non-null  float64
 52  ID                   17981 non-null  int64
 53  LAM                  15952 non-null  float64
 54  LB                   15952 non-null  float64
 55  LCB                  15952 non-null  float64
 56  LCM                  15952 non-null  float64
 57  LDM                  15952 non-null  float64
 58  LF                   15952 non-null  float64
 59  LM                   15952 non-null  float64
 60  LS                   15952 non-null  float64
 61  LW                   15952 non-null  float64
 62  LWB                  15952 non-null  float64
 63  Preferred Positions  17981 non-null  object
 64  RAM                  15952 non-null  float64
 65  RB                   15952 non-null  float64
 66  RCB                  15952 non-null  float64
 67  RCM                  15952 non-null  float64
 68  RDM                  15952 non-null  float64
 69  RF                   15952 non-null  float64
 70  RM                   15952 non-null  float64
 71  RS                   15952 non-null  float64
 72  RW                   15952 non-null  float64
 73  RWB                  15952 non-null  float64
 74  ST                   15952 non-null  float64
dtypes: float64(26), int64(6), object(43)
memory usage: 10.3+ MB

In [17]:
df.describe()

,Index,Age,Overall,Potential,Special,CAM,CB,CDM,CF,CM,ID,LAM,LB,LCB,LCM,LDM,LF,LM,LS,LW,LWB,RAM,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST
count,17981.000000,17981.000000,17981.000000,17981.000000,17981.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,17981.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000,15952.000000
mean,8990.000000,25.144541,66.247984,71.190813,1594.095100,59.251755,55.550464,56.865283,59.030028,58.506833,207658.710138,59.251755,56.979689,55.550464,58.506833,56.865283,59.030028,60.057736,58.204050,59.359265,57.698721,59.251755,56.979689,55.550464,58.506833,56.865283,59.030028,60.057736,58.204050,59.359265,57.698721,58.204050
std,5190.811931,4.614272,6.987965,6.102199,272.151435,9.880164,12.192579,10.310178,9.926988,8.888040,32291.667313,9.880164,9.791627,12.192579,8.888040,10.310178,9.926988,9.349180,9.181392,9.978084,9.142825,9.880164,9.791627,12.192579,8.888040,10.310178,9.926988,9.349180,9.181392,9.978084,9.142825,9.181392
min,0.000000,16.000000,46.000000,46.000000,728.000000,27.000000,25.000000,26.000000,27.000000,30.000000,16.000000,27.000000,30.000000,25.000000,30.000000,26.000000,27.000000,28.000000,31.000000,26.000000,31.000000,27.000000,30.000000,25.000000,30.000000,26.000000,27.000000,28.000000,31.000000,26.000000,31.000000,31.000000
25%,4495.000000,21.000000,62.000000,67.000000,1449.000000,53.000000,45.000000,49.000000,53.000000,53.000000,192622.000000,53.000000,50.000000,45.000000,53.000000,49.000000,53.000000,54.000000,52.000000,53.000000,51.000000,53.000000,50.000000,45.000000,53.000000,49.000000,53.000000,54.000000,52.000000,53.000000,51.000000,52.000000
50%,8990.000000,25.000000,66.000000,71.000000,1633.000000,60.000000,57.000000,58.000000,60.000000,59.000000,214057.000000,60.000000,58.000000,57.000000,59.000000,58.000000,60.000000,61.000000,59.000000,60.000000,58.000000,60.000000,58.000000,57.000000,59.000000,58.000000,60.000000,61.000000,59.000000,60.000000,58.000000,59.000000
75%,13485.000000,28.000000,71.000000,75.000000,1786.000000,66.000000,65.000000,65.000000,66.000000,65.000000,231448.000000,66.000000,64.000000,65.000000,65.000000,65.000000,66.000000,67.000000,65.000000,66.000000,64.000000,66.000000,64.000000,65.000000,65.000000,65.000000,66.000000,67.000000,65.000000,66.000000,64.000000,65.000000
max,17980.000000,47.000000,94.000000,94.000000,2291.000000,92.000000,87.000000,85.000000,92.000000,87.000000,241219.000000,92.000000,84.000000,87.000000,87.000000,85.000000,92.000000,90.000000,92.000000,91.000000,84.000000,92.000000,84.000000,87.000000,87.000000,85.000000,92.000000,90.000000,92.000000,91.000000,84.000000,92.000000

In [18]:
subdf1 = df.loc[:,'Special':'LWB']
subdf2 = df.loc[:,'RAM':]
subdf = pd.concat([subdf1,subdf2], axis=1)
subdf.head()

,Special,Acceleration,Aggression,Agility,Balance,Ball control,Composure,Crossing,Curve,Dribbling,Finishing,Free kick accuracy,GK diving,GK handling,GK kicking,GK positioning,GK reflexes,Heading accuracy,Interceptions,Jumping,Long passing,Long shots,Marking,Penalties,Positioning,Reactions,Short passing,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,CAM,CB,CDM,CF,CM,ID,LAM,LB,LCB,LCM,LDM,LF,LM,LS,LW,LWB,RAM,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST
0,2228,89,63,89,63,93,95,85,81,91,94,76,7,11,15,14,11,88,29,95,77,92,22,85,95,96,83,94,23,91,92,31,80,85,88,89.0,53.0,62.0,91.0,82.0,20801,89.0,61.0,53.0,82.0,62.0,91.0,89.0,92.0,91.0,66.0,89.0,61.0,53.0,82.0,62.0,91.0,89.0,92.0,91.0,66.0,92.0
1,2154,92,48,90,95,95,96,77,89,97,95,90,6,11,15,14,8,71,22,68,87,88,13,74,93,95,88,85,26,87,73,28,59,90,85,92.0,45.0,59.0,92.0,84.0,158023,92.0,57.0,45.0,84.0,59.0,92.0,90.0,88.0,91.0,62.0,92.0,57.0,45.0,84.0,59.0,92.0,90.0,88.0,91.0,62.0,88.0
2,2100,94,56,96,82,95,92,75,81,96,89,84,9,9,15,15,11,62,36,61,75,77,21,81,90,88,81,80,33,90,78,24,53,80,83,88.0,46.0,59.0,88.0,79.0,190871,88.0,59.0,46.0,79.0,59.0,88.0,87.0,84.0,89.0,64.0,88.0,59.0,46.0,79.0,59.0,88.0,87.0,84.0,89.0,64.0,84.0
3,2291,88,78,86,60,91,83,77,86,86,94,84,27,25,31,33,37,77,41,69,64,86,30,85,92,93,83,87,38,77,89,45,80,84,88,87.0,58.0,65.0,88.0,80.0,176580,87.0,64.0,58.0,80.0,65.0,88.0,85.0,88.0,87.0,68.0,87.0,64.0,58.0,80.0,65.0,88.0,85.0,88.0,87.0,68.0,88.0
4,1493,58,29,52,35,48,70,15,14,30,13,11,91,90,95,91,89,25,30,78,59,16,10,47,12,85,55,25,11,61,44,10,83,70,11,NaN,NaN,NaN,NaN,NaN,167495,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
subdf = subdf.astype('str').replace('\+.*','',regex=True).replace('\-.*','',regex=True)

In [20]:
subdf = subdf.astype('float64')

In [21]:
subdf.head()

,Special,Acceleration,Aggression,Agility,Balance,Ball control,Composure,Crossing,Curve,Dribbling,Finishing,Free kick accuracy,GK diving,GK handling,GK kicking,GK positioning,GK reflexes,Heading accuracy,Interceptions,Jumping,Long passing,Long shots,Marking,Penalties,Positioning,Reactions,Short passing,Shot power,Sliding tackle,Sprint speed,Stamina,Standing tackle,Strength,Vision,Volleys,CAM,CB,CDM,CF,CM,ID,LAM,LB,LCB,LCM,LDM,LF,LM,LS,LW,LWB,RAM,RB,RCB,RCM,RDM,RF,RM,RS,RW,RWB,ST
0,2228.0,89.0,63.0,89.0,63.0,93.0,95.0,85.0,81.0,91.0,94.0,76.0,7.0,11.0,15.0,14.0,11.0,88.0,29.0,95.0,77.0,92.0,22.0,85.0,95.0,96.0,83.0,94.0,23.0,91.0,92.0,31.0,80.0,85.0,88.0,89.0,53.0,62.0,91.0,82.0,20801.0,89.0,61.0,53.0,82.0,62.0,91.0,89.0,92.0,91.0,66.0,89.0,61.0,53.0,82.0,62.0,91.0,89.0,92.0,91.0,66.0,92.0
1,2154.0,92.0,48.0,90.0,95.0,95.0,96.0,77.0,89.0,97.0,95.0,90.0,6.0,11.0,15.0,14.0,8.0,71.0,22.0,68.0,87.0,88.0,13.0,74.0,93.0,95.0,88.0,85.0,26.0,87.0,73.0,28.0,59.0,90.0,85.0,92.0,45.0,59.0,92.0,84.0,158023.0,92.0,57.0,45.0,84.0,59.0,92.0,90.0,88.0,91.0,62.0,92.0,57.0,45.0,84.0,59.0,92.0,90.0,88.0,91.0,62.0,88.0
2,2100.0,94.0,56.0,96.0,82.0,95.0,92.0,75.0,81.0,96.0,89.0,84.0,9.0,9.0,15.0,15.0,11.0,62.0,36.0,61.0,75.0,77.0,21.0,81.0,90.0,88.0,81.0,80.0,33.0,90.0,78.0,24.0,53.0,80.0,83.0,88.0,46.0,59.0,88.0,79.0,190871.0,88.0,59.0,46.0,79.0,59.0,88.0,87.0,84.0,89.0,64.0,88.0,59.0,46.0,79.0,59.0,88.0,87.0,84.0,89.0,64.0,84.0
3,2291.0,88.0,78.0,86.0,60.0,91.0,83.0,77.0,86.0,86.0,94.0,84.0,27.0,25.0,31.0,33.0,37.0,77.0,41.0,69.0,64.0,86.0,30.0,85.0,92.0,93.0,83.0,87.0,38.0,77.0,89.0,45.0,80.0,84.0,88.0,87.0,58.0,65.0,88.0,80.0,176580.0,87.0,64.0,58.0,80.0,65.0,88.0,85.0,88.0,87.0,68.0,87.0,64.0,58.0,80.0,65.0,88.0,85.0,88.0,87.0,68.0,88.0
4,1493.0,58.0,29.0,52.0,35.0,48.0,70.0,15.0,14.0,30.0,13.0,11.0,91.0,90.0,95.0,91.0,89.0,25.0,30.0,78.0,59.0,16.0,10.0,47.0,12.0,85.0,55.0,25.0,11.0,61.0,44.0,10.0,83.0,70.0,11.0,NaN,NaN,NaN,NaN,NaN,167495.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df[subdf.columns] = subdf

In [23]:
df['Position'] = df['Preferred Positions'].str.split(' ').str[0]

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17981 entries, 0 to 17980
Data columns (total 76 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Index                17981 non-null  int64
 1   Name                 17981 non-null  object
 2   Age                  17981 non-null  int64
 3   Photo                17981 non-null  object
 4   Nationality          17981 non-null  object
 5   Flag                 17981 non-null  object
 6   Overall              17981 non-null  int64
 7   Potential            17981 non-null  int64
 8   Club                 17733 non-null  object
 9   Club Logo            17981 non-null  object
 10  Value                17981 non-null  object
 11  Wage                 17981 non-null  object
 12  Special              17981 non-null  float64
 13  Acceleration         17981 non-null  float64
 14  Aggression           17981 non-null  float64
 15  Agility              17981 non-null  float64
 16  Balance              17981 non-null  float64
 17  Ball control         17981 non-null  float64
 18  Composure            17981 non-null  float64
 19  Crossing             17981 non-null  float64
 20  Curve                17981 non-null  float64
 21  Dribbling            17981 non-null  float64
 22  Finishing            17981 non-null  float64
 23  Free kick accuracy   17981 non-null  float64
 24  GK diving            17981 non-null  float64
 25  GK handling          17981 non-null  float64
 26  GK kicking           17981 non-null  float64
 27  GK positioning       17981 non-null  float64
 28  GK reflexes          17981 non-null  float64
 29  Heading accuracy     17981 non-null  float64
 30  Interceptions        17981 non-null  float64
 31  Jumping              17981 non-null  float64
 32  Long passing         17981 non-null  float64
 33  Long shots           17981 non-null  float64
 34  Marking              17981 non-null  float64
 35  Penalties            17981 non-null  float64
 36  Positioning          17981 non-null  float64
 37  Reactions            17981 non-null  float64
 38  Short passing        17981 non-null  float64
 39  Shot power           17981 non-null  float64
 40  Sliding tackle       17981 non-null  float64
 41  Sprint speed         17981 non-null  float64
 42  Stamina              17981 non-null  float64
 43  Standing tackle      17981 non-null  float64
 44  Strength             17981 non-null  float64
 45  Vision               17981 non-null  float64
 46  Volleys              17981 non-null  float64
 47  CAM                  15952 non-null  float64
 48  CB                   15952 non-null  float64
 49  CDM                  15952 non-null  float64
 50  CF                   15952 non-null  float64
 51  CM                   15952 non-null  float64
 52  ID                   17981 non-null  float64
 53  LAM                  15952 non-null  float64
 54  LB                   15952 non-null  float64
 55  LCB                  15952 non-null  float64
 56  LCM                  15952 non-null  float64
 57  LDM                  15952 non-null  float64
 58  LF                   15952 non-null  float64
 59  LM                   15952 non-null  float64
 60  LS                   15952 non-null  float64
 61  LW                   15952 non-null  float64
 62  LWB                  15952 non-null  float64
 63  Preferred Positions  17981 non-null  object
 64  RAM                  15952 non-null  float64
 65  RB                   15952 non-null  float64
 66  RCB                  15952 non-null  float64
 67  RCM                  15952 non-null  float64
 68  RDM                  15952 non-null  float64
 69  RF                   15952 non-null  float64
 70  RM                   15952 non-null  float64
 71  RS                   15952 non-null  float64
 72  RW                   15952 non-null  float64
 73  RWB                  15952 non-null  float64
 74  ST                   15952 non-null  float64
 75  Position             17981 non-null  object
dtypes: float64(62), int64(4), object(10)
memory usage: 10.4+ MB

In [27]:
df.to_csv('fifa18-cleaned.csv',index=None)