#1

In [13]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [14]:
X,y = load_iris(return_X_y=True)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [ ]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [17]:
X_test_scaled

array([[-1.01618886,  0.52669736, -1.32841428, -1.31999078],
       [-0.89745209,  1.65937986, -1.0474666 , -1.05839062],
       [ 1.00233624,  0.52669736,  1.08773577,  1.16521069],
       [-0.18503147, -0.60598514,  0.41346134,  0.11881007],
       [-0.42250501, -1.73866764,  0.13251366,  0.11881007],
       [-0.89745209,  0.75323386, -1.27222475, -1.31999078],
       [ 0.52738916, -0.37944864,  1.03154624,  0.77281046],
       [-0.54124178,  0.75323386, -1.15984568, -1.31999078],
       [ 0.28991561, -0.15291214,  0.46965087,  0.24961015],
       [-0.54124178,  0.75323386, -1.27222475, -1.05839062],
       [-1.01618886,  0.75323386, -1.21603521, -1.05839062],
       [ 2.18970394, -0.60598514,  1.64963113,  1.03441061],
       [ 0.05244207, -0.15291214,  0.24489273,  0.38041022],
       [ 0.52738916, -1.73866764,  0.3572718 ,  0.11881007],
       [-1.13492563,  1.20630686, -1.32841428, -1.45079086],
       [-0.0662947 , -1.05905814,  0.13251366, -0.01199001],
       [-1.13492563,  0.07362436, -1.27222475, -1.45079086],
       [ 1.23980978,  0.30016086,  1.08773577,  1.42681084],
       [-0.18503147, -0.37944864,  0.24489273,  0.11881007],
       [ 0.05244207,  0.30016086,  0.58202995,  0.77281046],
       [-1.01618886, -2.41827714, -0.14843402, -0.27359016],
       [-1.2536624 ,  0.75323386, -1.0474666 , -1.31999078],
       [ 0.88359947, -0.37944864,  0.46965087,  0.11881007],
       [ 0.28991561, -0.15291214,  0.63821948,  0.77281046],
       [-1.13492563, -0.15291214, -1.32841428, -1.31999078],
       [ 1.00233624,  0.07362436,  0.52584041,  0.38041022],
       [-1.13492563, -1.51213114, -0.2608131 , -0.27359016],
       [ 0.52738916,  0.52669736,  1.25630438,  1.688411  ],
       [ 0.64612593, -0.83252164,  0.86297763,  0.90361053],
       [ 1.12107301, -0.15291214,  0.9753567 ,  1.16521069]])

#2

In [24]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [25]:
X_test_scaled

array([[ 0.19444444,  0.5       ,  0.06779661,  0.04166667],
       [ 0.22222222,  0.72727273,  0.15254237,  0.125     ],
       [ 0.66666667,  0.5       ,  0.79661017,  0.83333333],
       [ 0.38888889,  0.27272727,  0.59322034,  0.5       ],
       [ 0.33333333,  0.04545455,  0.50847458,  0.5       ],
       [ 0.22222222,  0.54545455,  0.08474576,  0.04166667],
       [ 0.55555556,  0.31818182,  0.77966102,  0.70833333],
       [ 0.30555556,  0.54545455,  0.11864407,  0.04166667],
       [ 0.5       ,  0.36363636,  0.61016949,  0.54166667],
       [ 0.30555556,  0.54545455,  0.08474576,  0.125     ],
       [ 0.19444444,  0.54545455,  0.10169492,  0.125     ],
       [ 0.94444444,  0.27272727,  0.96610169,  0.79166667],
       [ 0.44444444,  0.36363636,  0.54237288,  0.58333333],
       [ 0.55555556,  0.04545455,  0.57627119,  0.5       ],
       [ 0.16666667,  0.63636364,  0.06779661,  0.        ],
       [ 0.41666667,  0.18181818,  0.50847458,  0.45833333],
       [ 0.16666667,  0.40909091,  0.08474576,  0.        ],
       [ 0.72222222,  0.45454545,  0.79661017,  0.91666667],
       [ 0.38888889,  0.31818182,  0.54237288,  0.5       ],
       [ 0.44444444,  0.45454545,  0.6440678 ,  0.70833333],
       [ 0.19444444, -0.09090909,  0.42372881,  0.375     ],
       [ 0.13888889,  0.54545455,  0.15254237,  0.04166667],
       [ 0.63888889,  0.31818182,  0.61016949,  0.5       ],
       [ 0.5       ,  0.36363636,  0.66101695,  0.70833333],
       [ 0.16666667,  0.36363636,  0.06779661,  0.04166667],
       [ 0.66666667,  0.40909091,  0.62711864,  0.58333333],
       [ 0.16666667,  0.09090909,  0.38983051,  0.375     ],
       [ 0.55555556,  0.5       ,  0.84745763,  1.        ],
       [ 0.58333333,  0.22727273,  0.72881356,  0.75      ],
       [ 0.69444444,  0.36363636,  0.76271186,  0.83333333]])

In [26]:
import numpy as np
X_min = np.min(X_train, axis=0)
X_max = np.max(X_train, axis=0)

(X_train - X_min) / (X_max - X_min)

array([[0.55555556, 0.54545455, 0.77966102, 0.95833333],
       [0.30555556, 0.68181818, 0.08474576, 0.04166667],
       [0.19444444, 0.04545455, 0.38983051, 0.375     ],
       [0.25      , 0.59090909, 0.08474576, 0.04166667],
       [0.38888889, 0.36363636, 0.54237288, 0.45833333],
       [0.05555556, 0.04545455, 0.05084746, 0.08333333],
       [0.47222222, 0.36363636, 0.6440678 , 0.70833333],
       [0.19444444, 0.36363636, 0.10169492, 0.04166667],
       [0.47222222, 0.        , 0.6779661 , 0.58333333],
       [0.        , 0.36363636, 0.01694915, 0.        ],
       [0.66666667, 0.40909091, 0.77966102, 0.95833333],
       [0.91666667, 0.36363636, 0.94915254, 0.83333333],
       [1.        , 0.72727273, 0.91525424, 0.79166667],
       [0.61111111, 0.36363636, 0.76271186, 0.70833333],
       [0.19444444, 0.63636364, 0.06779661, 0.04166667],
       [0.72222222, 0.40909091, 0.66101695, 0.58333333],
       [0.58333333, 0.27272727, 0.77966102, 0.875     ],
       [0.13888889, 0.40909091, 0.10169492, 0.04166667],
       [0.25      , 0.22727273, 0.49152542, 0.54166667],
       [0.13888889, 0.36363636, 0.06779661, 0.08333333],
       [0.30555556, 0.77272727, 0.11864407, 0.125     ],
       [0.52777778, 0.54545455, 0.74576271, 0.91666667],
       [0.58333333, 0.45454545, 0.59322034, 0.58333333],
       [0.44444444, 0.36363636, 0.69491525, 0.70833333],
       [0.22222222, 0.59090909, 0.06779661, 0.08333333],
       [0.22222222, 0.72727273, 0.08474576, 0.08333333],
       [0.52777778, 0.        , 0.59322034, 0.58333333],
       [0.38888889, 0.72727273, 0.11864407, 0.08333333],
       [0.30555556, 0.36363636, 0.59322034, 0.58333333],
       [0.66666667, 0.5       , 0.79661017, 1.        ],
       [0.36111111, 0.22727273, 0.54237288, 0.5       ],
       [0.94444444, 0.36363636, 0.86440678, 0.91666667],
       [0.47222222, 0.54545455, 0.59322034, 0.625     ],
       [0.47222222, 0.31818182, 0.59322034, 0.58333333],
       [0.41666667, 0.81818182, 0.03389831, 0.04166667],
       [0.22222222, 0.13636364, 0.33898305, 0.41666667],
       [0.25      , 0.86363636, 0.08474576, 0.        ],
       [0.61111111, 0.27272727, 0.61016949, 0.58333333],
       [0.19444444, 0.59090909, 0.05084746, 0.08333333],
       [0.77777778, 0.36363636, 0.83050847, 0.83333333],
       [0.36111111, 0.36363636, 0.52542373, 0.5       ],
       [0.33333333, 0.18181818, 0.57627119, 0.45833333],
       [0.38888889, 0.18181818, 0.42372881, 0.375     ],
       [0.66666667, 0.36363636, 0.71186441, 0.91666667],
       [0.58333333, 0.27272727, 0.77966102, 0.83333333],
       [0.69444444, 0.45454545, 0.83050847, 0.91666667],
       [0.63888889, 0.36363636, 0.57627119, 0.54166667],
       [0.66666667, 0.13636364, 0.81355932, 0.70833333],
       [0.69444444, 0.27272727, 0.6440678 , 0.54166667],
       [0.08333333, 0.54545455, 0.06779661, 0.08333333],
       [0.80555556, 0.45454545, 0.84745763, 0.70833333],
       [0.41666667, 0.22727273, 0.69491525, 0.75      ],
       [0.94444444, 0.72727273, 0.96610169, 0.875     ],
       [0.33333333, 0.90909091, 0.06779661, 0.04166667],
       [0.80555556, 0.36363636, 0.81355932, 0.625     ],
       [0.72222222, 0.40909091, 0.74576271, 0.83333333],
       [0.02777778, 0.45454545, 0.05084746, 0.04166667],
       [0.55555556, 0.13636364, 0.66101695, 0.58333333],
       [0.41666667, 0.22727273, 0.69491525, 0.75      ],
       [0.33333333, 0.09090909, 0.45762712, 0.375     ],
       [0.55555556, 0.22727273, 0.66101695, 0.70833333],
       [0.47222222, 0.        , 0.50847458, 0.375     ],
       [0.41666667, 0.22727273, 0.52542373, 0.375     ],
       [0.5       , 0.31818182, 0.62711864, 0.54166667],
       [0.16666667, 0.40909091, 0.08474576, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.61111111, 0.45454545, 0.69491525, 0.79166667],
       [0.33333333, 0.13636364, 0.50847458, 0.5       ],
       [0.19444444, 0.59090909, 0.10169492, 0.20833333],
       [0.58333333, 0.45454545, 0.72881356, 0.91666667],
       [0.13888889, 0.36363636, 0.06779661, 0.        ],
       [0.36111111, 0.13636364, 0.49152542, 0.41666667],
       [0.38888889, 0.27272727, 0.52542373, 0.5       ],
       [0.72222222, 0.40909091, 0.69491525, 0.91666667],
       [0.02777778, 0.36363636, 0.05084746, 0.04166667],
       [0.52777778, 0.27272727, 0.6440678 , 0.70833333],
       [0.75      , 0.45454545, 0.62711864, 0.54166667],
       [0.66666667, 0.36363636, 0.6779661 , 0.66666667],
       [0.02777778, 0.31818182, 0.06779661, 0.04166667],
       [0.30555556, 0.77272727, 0.05084746, 0.125     ],
       [0.5       , 0.18181818, 0.77966102, 0.54166667],
       [0.94444444, 0.18181818, 1.        , 0.91666667],
       [0.58333333, 0.31818182, 0.55932203, 0.5       ],
       [0.86111111, 0.27272727, 0.86440678, 0.75      ],
       [0.22222222, 0.68181818, 0.08474576, 0.125     ],
       [0.11111111, 0.45454545, 0.05084746, 0.04166667],
       [0.80555556, 0.63636364, 0.86440678, 1.        ],
       [0.55555556, 0.13636364, 0.6779661 , 0.75      ],
       [0.5       , 0.27272727, 0.62711864, 0.45833333],
       [0.19444444, 0.54545455, 0.08474576, 0.04166667],
       [0.55555556, 0.5       , 0.62711864, 0.625     ],
       [0.08333333, 0.40909091, 0.08474576, 0.04166667],
       [0.55555556, 0.27272727, 0.69491525, 0.58333333],
       [0.58333333, 0.40909091, 0.76271186, 0.70833333],
       [0.27777778, 0.68181818, 0.08474576, 0.04166667],
       [0.11111111, 0.45454545, 0.10169492, 0.04166667],
       [0.52777778, 0.31818182, 0.55932203, 0.5       ],
       [0.83333333, 0.31818182, 0.89830508, 0.70833333],
       [0.25      , 0.54545455, 0.06779661, 0.04166667],
       [0.33333333, 0.59090909, 0.05084746, 0.04166667],
       [0.66666667, 0.40909091, 0.57627119, 0.54166667],
       [0.22222222, 0.59090909, 0.06779661, 0.04166667],
       [0.41666667, 0.22727273, 0.49152542, 0.45833333],
       [0.13888889, 0.54545455, 0.10169492, 0.04166667],
       [0.08333333, 0.63636364, 0.        , 0.04166667],
       [0.61111111, 0.36363636, 0.71186441, 0.79166667],
       [0.5       , 0.27272727, 0.50847458, 0.5       ],
       [0.19444444, 0.45454545, 0.03389831, 0.04166667],
       [0.38888889, 0.13636364, 0.6779661 , 0.79166667],
       [0.22222222, 0.5       , 0.11864407, 0.16666667],
       [0.41666667, 0.27272727, 0.69491525, 0.95833333],
       [0.36111111, 0.36363636, 0.59322034, 0.58333333],
       [0.36111111, 0.27272727, 0.66101695, 0.79166667],
       [0.22222222, 0.72727273, 0.10169492, 0.04166667],
       [0.61111111, 0.36363636, 0.81355932, 0.875     ],
       [0.08333333, 0.45454545, 0.06779661, 0.04166667],
       [0.16666667, 0.13636364, 0.59322034, 0.66666667],
       [0.47222222, 0.22727273, 0.69491525, 0.625     ],
       [0.33333333, 0.09090909, 0.47457627, 0.41666667],
       [0.36111111, 0.31818182, 0.44067797, 0.5       ]])

#3

In [36]:
from sklearn.datasets import fetch_openml
from sklearn.preprocessing import OrdinalEncoder

In [37]:
data = fetch_openml("car", as_frame=True).frame

c:\dev\venv\Lib\site-packages\sklearn\datasets\_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name car exist. Versions may be fundamentally different, returning version 2. Available versions:
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=991
- version 3, status: active
  url: https://www.openml.org/search?type=data&id=40975

  warn(warning_msg)

In [38]:
data

     buying  maint  doors persons lug_boot safety binaryClass
0     vhigh  vhigh      2       2    small    low           P
1     vhigh  vhigh      2       2    small    med           P
2     vhigh  vhigh      2       2    small   high           P
3     vhigh  vhigh      2       2      med    low           P
4     vhigh  vhigh      2       2      med    med           P
...     ...    ...    ...     ...      ...    ...         ...
1723    low    low  5more    more      med    med           N
1724    low    low  5more    more      med   high           N
1725    low    low  5more    more      big    low           P
1726    low    low  5more    more      big    med           N
1727    low    low  5more    more      big   high           N

[1728 rows x 7 columns]

In [39]:
columns_to_encode = ["lug_boot", "safety"]

encoder = OrdinalEncoder(
    categories= [
        ["small", "med", "big"],
        ["low", "med", "high"]
    ]
)

data[columns_to_encode] = encoder.fit_transform(data[columns_to_encode])

In [40]:
data

     buying  maint  doors persons  lug_boot  safety binaryClass
0     vhigh  vhigh      2       2       0.0     0.0           P
1     vhigh  vhigh      2       2       0.0     1.0           P
2     vhigh  vhigh      2       2       0.0     2.0           P
3     vhigh  vhigh      2       2       1.0     0.0           P
4     vhigh  vhigh      2       2       1.0     1.0           P
...     ...    ...    ...     ...       ...     ...         ...
1723    low    low  5more    more       1.0     1.0           N
1724    low    low  5more    more       1.0     2.0           N
1725    low    low  5more    more       2.0     0.0           P
1726    low    low  5more    more       2.0     1.0           N
1727    low    low  5more    more       2.0     2.0           N

[1728 rows x 7 columns]

In [41]:
encoder.inverse_transform(data[columns_to_encode])

array([['small', 'low'],
       ['small', 'med'],
       ['small', 'high'],
       ...,
       ['big', 'low'],
       ['big', 'med'],
       ['big', 'high']], shape=(1728, 2), dtype=object)

In [42]:
data = fetch_openml("adult", as_frame=True).frame

c:\dev\venv\Lib\site-packages\sklearn\datasets\_openml.py:328: UserWarning: Multiple active versions of the dataset matching the name adult exist. Versions may be fundamentally different, returning version 1. Available versions:
- version 1, status: active
  url: https://www.openml.org/search?type=data&id=179
- version 2, status: active
  url: https://www.openml.org/search?type=data&id=1590

  warn(warning_msg)

In [43]:
data

      age         workclass  fnlwgt  ... hoursperweek  native-country  class
0       2         State-gov   77516  ...            2   United-States  <=50K
1       3  Self-emp-not-inc   83311  ...            0   United-States  <=50K
2       2           Private  215646  ...            2   United-States  <=50K
3       3           Private  234721  ...            2   United-States  <=50K
4       1           Private  338409  ...            2            Cuba  <=50K
...    ..               ...     ...  ...          ...             ...    ...
48837   2           Private  215419  ...            2   United-States  <=50K
48838   4               NaN  321403  ...            2   United-States  <=50K
48839   2           Private  374983  ...            3   United-States  <=50K
48840   2           Private   83891  ...            2   United-States  <=50K
48841   1      Self-emp-inc  182148  ...            3   United-States   >50K

[48842 rows x 15 columns]

#4

In [44]:
from sklearn.preprocessing import OneHotEncoder

In [45]:
data.occupation.value_counts()

occupation
Prof-specialty       6172
Craft-repair         6112
Exec-managerial      6086
Adm-clerical         5611
Sales                5504
Other-service        4923
Machine-op-inspct    3022
Transport-moving     2355
Handlers-cleaners    2072
Farming-fishing      1490
Tech-support         1446
Protective-serv       983
Priv-house-serv       242
Armed-Forces           15
Name: count, dtype: int64

In [49]:
import pandas as pd

encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
encoded_values = encoder.fit_transform(data[["occupation", "race"]])
new_cols = encoder.get_feature_names_out(["occupation", "race"])

In [50]:
encoded_values

array([[1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], shape=(48842, 20))

In [51]:
new_cols

array(['occupation_Adm-clerical', 'occupation_Armed-Forces',
       'occupation_Craft-repair', 'occupation_Exec-managerial',
       'occupation_Farming-fishing', 'occupation_Handlers-cleaners',
       'occupation_Machine-op-inspct', 'occupation_Other-service',
       'occupation_Priv-house-serv', 'occupation_Prof-specialty',
       'occupation_Protective-serv', 'occupation_Sales',
       'occupation_Tech-support', 'occupation_Transport-moving',
       'occupation_nan', 'race_Amer-Indian-Eskimo',
       'race_Asian-Pac-Islander', 'race_Black', 'race_Other',
       'race_White'], dtype=object)

In [52]:
df_encoded = pd.DataFrame(encoded_values, columns=new_cols, index=data.index)
data_final = pd.concat(
    [data.drop(columns=["occupation", "race"]), df_encoded],
    axis=1
)

In [53]:
data_final

      age         workclass  fnlwgt  ... race_Black  race_Other race_White
0       2         State-gov   77516  ...        0.0         0.0        1.0
1       3  Self-emp-not-inc   83311  ...        0.0         0.0        1.0
2       2           Private  215646  ...        0.0         0.0        1.0
3       3           Private  234721  ...        1.0         0.0        0.0
4       1           Private  338409  ...        1.0         0.0        0.0
...    ..               ...     ...  ...        ...         ...        ...
48837   2           Private  215419  ...        0.0         0.0        1.0
48838   4               NaN  321403  ...        1.0         0.0        0.0
48839   2           Private  374983  ...        0.0         0.0        1.0
48840   2           Private   83891  ...        0.0         0.0        0.0
48841   1      Self-emp-inc  182148  ...        0.0         0.0        1.0

[48842 rows x 33 columns]